# Generated by Django 5.0.6 on 2024-06-22 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hermite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x_values', models.CharField(max_length=100, verbose_name='Valores de X')),
                ('y_values', models.CharField(max_length=100, null=True, verbose_name='Valores de Y')),
                ('y_derivate', models.CharField(max_length=100, null=True, verbose_name='Y derivada')),
            ],
            options={
                'verbose_name': 'Metodo de Hermite',
                'verbose_name_plural': 'Metodode Hermite',
                'db_table': 'hermite',
            },
        ),
    ]
